; Auto-generated. Do not edit!


(cl:in-package sound_play-msg)


;//! \htmlinclude SoundRequestGoal.msg.html

(cl:defclass <SoundRequestGoal> (roslisp-msg-protocol:ros-message)
  ((sound_request
    :reader sound_request
    :initarg :sound_request
    :type sound_play-msg:SoundRequest
    :initform (cl:make-instance 'sound_play-msg:SoundRequest)))
)

(cl:defclass SoundRequestGoal (<SoundRequestGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoundRequestGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoundRequestGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sound_play-msg:<SoundRequestGoal> is deprecated: use sound_play-msg:SoundRequestGoal instead.")))

(cl:ensure-generic-function 'sound_request-val :lambda-list '(m))
(cl:defmethod sound_request-val ((m <SoundRequestGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sound_play-msg:sound_request-val is deprecated.  Use sound_play-msg:sound_request instead.")
  (sound_request m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoundRequestGoal>) ostream)
  "Serializes a message object of type '<SoundRequestGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'sound_request) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoundRequestGoal>) istream)
  "Deserializes a message object of type '<SoundRequestGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'sound_request) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoundRequestGoal>)))
  "Returns string type for a message object of type '<SoundRequestGoal>"
  "sound_play/SoundRequestGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoundRequestGoal)))
  "Returns string type for a message object of type 'SoundRequestGoal"
  "sound_play/SoundRequestGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoundRequestGoal>)))
  "Returns md5sum for a message object of type '<SoundRequestGoal>"
  "3bd5e9e7f60b85cc6f1b7662fe6e1903")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoundRequestGoal)))
  "Returns md5sum for a message object of type 'SoundRequestGoal"
  "3bd5e9e7f60b85cc6f1b7662fe6e1903")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoundRequestGoal>)))
  "Returns full string definition for message of type '<SoundRequestGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%SoundRequest sound_request~%~%================================================================================~%MSG: sound_play/SoundRequest~%# IMPORTANT: You should never have to generate this message yourself.~%# Use the sound_play::SoundClient C++ helper or the~%# sound_play.libsoundplay.SoundClient Python helper.~%~%# Sounds~%int8 BACKINGUP = 1~%int8 NEEDS_UNPLUGGING = 2~%int8 NEEDS_PLUGGING = 3~%int8 NEEDS_UNPLUGGING_BADLY = 4~%int8 NEEDS_PLUGGING_BADLY = 5~%~%# Sound identifiers that have special meaning~%int8 ALL = -1 # Only legal with PLAY_STOP~%int8 PLAY_FILE = -2~%int8 SAY = -3~%~%int8 sound # Selects which sound to play (see above)~%~%# Commands~%int8 PLAY_STOP = 0 # Stop this sound from playing~%int8 PLAY_ONCE = 1 # Play the sound once~%int8 PLAY_START = 2 # Play the sound in a loop until a stop request occurs~%~%int8 command # Indicates what to do with the sound~%~%# Volume at which to play the sound, with 0 as mute and 1.0 as 100%.~%float32 volume~%~%string arg # file name or text to say~%string arg2 # other arguments~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoundRequestGoal)))
  "Returns full string definition for message of type 'SoundRequestGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%SoundRequest sound_request~%~%================================================================================~%MSG: sound_play/SoundRequest~%# IMPORTANT: You should never have to generate this message yourself.~%# Use the sound_play::SoundClient C++ helper or the~%# sound_play.libsoundplay.SoundClient Python helper.~%~%# Sounds~%int8 BACKINGUP = 1~%int8 NEEDS_UNPLUGGING = 2~%int8 NEEDS_PLUGGING = 3~%int8 NEEDS_UNPLUGGING_BADLY = 4~%int8 NEEDS_PLUGGING_BADLY = 5~%~%# Sound identifiers that have special meaning~%int8 ALL = -1 # Only legal with PLAY_STOP~%int8 PLAY_FILE = -2~%int8 SAY = -3~%~%int8 sound # Selects which sound to play (see above)~%~%# Commands~%int8 PLAY_STOP = 0 # Stop this sound from playing~%int8 PLAY_ONCE = 1 # Play the sound once~%int8 PLAY_START = 2 # Play the sound in a loop until a stop request occurs~%~%int8 command # Indicates what to do with the sound~%~%# Volume at which to play the sound, with 0 as mute and 1.0 as 100%.~%float32 volume~%~%string arg # file name or text to say~%string arg2 # other arguments~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoundRequestGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'sound_request))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoundRequestGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SoundRequestGoal
    (cl:cons ':sound_request (sound_request msg))
))
