; Auto-generated. Do not edit!


(cl:in-package sound_play-msg)


;//! \htmlinclude SoundRequestFeedback.msg.html

(cl:defclass <SoundRequestFeedback> (roslisp-msg-protocol:ros-message)
  ((playing
    :reader playing
    :initarg :playing
    :type cl:boolean
    :initform cl:nil)
   (stamp
    :reader stamp
    :initarg :stamp
    :type cl:real
    :initform 0))
)

(cl:defclass SoundRequestFeedback (<SoundRequestFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SoundRequestFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SoundRequestFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name sound_play-msg:<SoundRequestFeedback> is deprecated: use sound_play-msg:SoundRequestFeedback instead.")))

(cl:ensure-generic-function 'playing-val :lambda-list '(m))
(cl:defmethod playing-val ((m <SoundRequestFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sound_play-msg:playing-val is deprecated.  Use sound_play-msg:playing instead.")
  (playing m))

(cl:ensure-generic-function 'stamp-val :lambda-list '(m))
(cl:defmethod stamp-val ((m <SoundRequestFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader sound_play-msg:stamp-val is deprecated.  Use sound_play-msg:stamp instead.")
  (stamp m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SoundRequestFeedback>) ostream)
  "Serializes a message object of type '<SoundRequestFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'playing) 1 0)) ostream)
  (cl:let ((__sec (cl:floor (cl:slot-value msg 'stamp)))
        (__nsec (cl:round (cl:* 1e9 (cl:- (cl:slot-value msg 'stamp) (cl:floor (cl:slot-value msg 'stamp)))))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __sec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 0) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __nsec) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __nsec) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SoundRequestFeedback>) istream)
  "Deserializes a message object of type '<SoundRequestFeedback>"
    (cl:setf (cl:slot-value msg 'playing) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((__sec 0) (__nsec 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __sec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 0) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __nsec) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __nsec) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'stamp) (cl:+ (cl:coerce __sec 'cl:double-float) (cl:/ __nsec 1e9))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SoundRequestFeedback>)))
  "Returns string type for a message object of type '<SoundRequestFeedback>"
  "sound_play/SoundRequestFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SoundRequestFeedback)))
  "Returns string type for a message object of type 'SoundRequestFeedback"
  "sound_play/SoundRequestFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SoundRequestFeedback>)))
  "Returns md5sum for a message object of type '<SoundRequestFeedback>"
  "237faa3e32b21b083f32acf5260255a4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SoundRequestFeedback)))
  "Returns md5sum for a message object of type 'SoundRequestFeedback"
  "237faa3e32b21b083f32acf5260255a4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SoundRequestFeedback>)))
  "Returns full string definition for message of type '<SoundRequestFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool playing~%time stamp~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SoundRequestFeedback)))
  "Returns full string definition for message of type 'SoundRequestFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool playing~%time stamp~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SoundRequestFeedback>))
  (cl:+ 0
     1
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SoundRequestFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SoundRequestFeedback
    (cl:cons ':playing (playing msg))
    (cl:cons ':stamp (stamp msg))
))
